# Generated by Django 5.2.3 on 2025-06-17 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_of_the_product', models.CharField()),
                ('color', models.CharField(max_length=255)),
                ('memory_size', models.IntegerField()),
                ('seller', models.CharField(max_length=255)),
                ('regular_price', models.IntegerField()),
                ('promotional_price', models.IntegerField()),
                ('product_code', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('series', models.CharField(max_length=255)),
                ('screen_diagonal', models.CharField(max_length=255)),
                ('display_resolution', models.CharField(max_length=255)),
                ('product_specifications', models.JSONField()),
            ],
            options={
                'verbose_name': 'Mobile',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField()),
                ('url', models.CharField()),
                ('all_product_photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='parser_app.mobile')),
            ],
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
