# Generated by Django 5.2.3 on 2025-06-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_mobile_photo_delete_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='all_product_photos',
            new_name='mobile_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='alt',
        ),
        migrations.AlterField(
            model_name='mobile',
            name='color',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='display_resolution',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='screen_diagonal',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='seller',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='series',
            field=models.CharField(),
        ),
    ]
